import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { prompt, image, model } = await request.json();

    if (!prompt || !image) {
      return NextResponse.json(
        { error: 'Prompt and image are required' },
        { status: 400 }
      );
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: 'API key not configured' },
        { status: 500 }
      );
    }

    // Extract base64 data from data URL
    let base64Data, mimeType;
    
    try {
      if (image.startsWith('data:')) {
        const [header, data] = image.split(',');
        base64Data = data;
        mimeType = header.split(':')[1].split(';')[0];
      } else {
        // If it's already base64 without data URL prefix
        base64Data = image;
        mimeType = 'image/jpeg'; // Default mime type
      }
      
      console.log('Image processing:', {
        hasDataPrefix: image.startsWith('data:'),
        mimeType,
        dataLength: base64Data?.length
      });
      
      if (!base64Data) {
        throw new Error('Invalid image data format');
      }
    } catch (error) {
      console.error('Image parsing error:', error);
      return NextResponse.json(
        { error: 'Invalid image data format' },
        { status: 400 }
      );
    }

    const requestBody = {
      contents: [{
        parts: [
          {
            text: `Edit this image: ${prompt}. Make the changes as requested.`
          },
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Data
            }
          }
        ]
      }],
      generationConfig: {
        temperature: 0.7,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 8192,
      }
    };

    console.log('Sending request to Gemini API:', {
      prompt: prompt.substring(0, 100) + '...',
      mimeType,
      dataSize: base64Data.length,
      hasInlineData: !!requestBody.contents[0].parts[1].inlineData
    });

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image-preview:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      }
    );

    if (!response.ok) {
      const error = await response.text();
      console.error('Gemini API error:', error);
      console.error('Response status:', response.status);
      return NextResponse.json(
        { error: `Failed to edit image: ${error}` },
        { status: response.status }
      );
    }

    const data = await response.json();
    console.log('Edit API Response:', data);
    
    // Check for API errors first
    if (data.error) {
      console.error('API Error:', data.error);
      return NextResponse.json(
        { error: `API Error: ${data.error.message || data.error}` },
        { status: 500 }
      );
    }
    
    // Return the full candidates structure that frontend expects
    if (data.candidates && data.candidates[0] && data.candidates[0].content && data.candidates[0].content.parts) {
      const images = data.candidates[0].content.parts
        .filter((part: any) => part.inlineData && part.inlineData.mimeType.startsWith('image/'));
      
      if (images.length > 0) {
        return NextResponse.json({ candidates: data.candidates });
      }
    }
    
    // If no images were generated, return an error
    return NextResponse.json({ 
      error: 'No edited images were generated by the API.' 
    }, { status: 500 });

  } catch (error) {
    console.error('Image editing error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}